### ISSUE TITLE
OPDS v2

### ISSUE THREAD

**Issue by binyaminyblatt** [anansi-project/opds-pse#13]
Please update the spec to comply with the new updated spec

**Comment by gotson** [comment]
can you maybe provide some more details ?

**Comment by binyaminyblatt** [comment]
I was just looking around on the specification form and it basically said that there's a new version of the specification and when I looked into it it didn't seem to include the add-ons you created so if I wanted to include your addon with the new version it wouldn't work

**Comment by gotson** [comment]
OPDS-PSE is only for OPDS v1.

OPDS v2 already has built-in support for the use cases covered by OPDS-PSE.
