### ISSUE TITLE
Update read progress

### ISSUE THREAD

**Issue by vuhe** [anansi-project/opds-pse#14]
Can PSE provide the format of specifications for synchronizing progress from the client to the server:

```xml
<link rel="http://vaemendis.net/opds-pse/stream"
      type="image/jpeg"
      href="/opds-comics/stream/1217?page={pageNumber}"
      pse:count="35"
      pse:lastRead="10"
      pse:lastReadDate="2010-01-10T10:01:11Z"
      pse:progress="/opds-comics/progress/1217?page={pageNumber}"
/>
```

`/opds-comics/progress/1217?page={pageNumber}` as an interface that can accept requests for the client to return the reading progress of this entry.

I read the opds specification and found that only v2 can provide progress synchronization related interfaces. However, since v2 has not yet been officially released, some of the client developers I use think that they need to wait for v2 to be officially released, and some are not very interested in adapting to the v2 protocol.

Can opds v1 also achieve progress synchronization by simply adding an interface?

Sorry if the language is inappropriate, I used google translate.

**Comment by gotson** [comment]
OPDS v2 is very much alive and used, the fact that the spec is a draft is not a blocker for implementation. For instance Komga [already implements](https://komga.org/docs/guides/opds/#opds-v2) OPDS v2 with the Progression API. On client side, Cantook implements OPDS v2 and the Progression API, and can be used with Komga to update read progress.

**Comment by vuhe** [comment]
Because the clients I often use are not actively adapted to OPDS, and there are still many that have not been adapted to OPDS v1. The way these clients synchronize reading progress is achieved by calling Komga's proprietary API, but due to the localization of the clients, I cannot give up using them.

I am using a simple OPDS server that I have written myself, so I am unable to use this method for progress synchronization. I will try to find other ways to adapt to these clients.

Finally, thank you for your reply and answer.
